name: Aws deployment
on:
  push:
    branches: [master]
jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
          python-version: 3.9
    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip
          pip install flake8
          sudo apt-get install python3-pip
          pip3 install markdown2
          pip3 install jinja2
    - name: run main.py file to create html files
      run: |
          python3 main.py
          
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2
  
    - name: copy files from output folder to aws ec2
      run: |
        scp -i aws_1.pem . ec2-user@ec2-3-224-202-156.compute-1.amazonaws.com:~/
        
        
