name: Aws deployment
on:
  push:
    branches: [master]
jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
          python-version: 3.9
    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip
          pip install flake8
          sudo apt-get install python3-pip
          pip3 install markdown2
          pip3 install jinja2
    - name: run main.py file to create html files
      run: |
          python3 main.py
          
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2
    - name: copy pem key file and known_hosts from s3 bucket to .ssh folder
      run: |
        mkdir ~/.ssh && cd ~/.ssh
        aws s3 cp s3://fahimweb/aws_fahimkk_1.pem .
        aws s3 cp s3://fahimweb/known_hosts .
        aws s3 cp s3://fahimweb/config .
        
    - name: copy files from output folder in github repo to aws ec2 instance
      run: |
        cd ~/.ssh
        scp -i aws_fahimkk_1.pem ../output/ ec2-user@ec2-3-224-202-156.compute-1.amazonaws.com:~/
